### ISSUE TITLE
Remove locl feature?

### ISSUE THREAD

**Issue by ayaka14732** [redchenjs/source-han-serif-classic#1]
When the locale is set to `zh` or `zh-Hant`, glyphs are not displayed in classic orthography. For example, the last stroke of 冬 goes down instead of going up.

This problem will be solved if the `locl` feature is removed. I believe that the feature is unnecessary for this font, as users may expect to use classic orthography in Chinese environments. Besides, removing the `locl` feature will make it possible to reduce the font size as many glyphs in this font will be unreachable and can therefore be removed.

**Comment by redchenjs** [comment]
@ayaka14732 Updated.

**Comment by ayaka14732** [comment]
Thanks for this quick update! However, the unused glyphs are not removed:

![image](https://user-images.githubusercontent.com/68557794/116636646-55858600-a994-11eb-80a5-e7f50c2718e4.png)

**Comment by redchenjs** [comment]
Hi @ayaka14732,

Glyphs that were only referenced in the `locl` feature have been removed. (removed by [`update.sh`](https://github.com/redchenjs/source-han-serif-classic/blob/master/update.sh), total 18534 glyphs)

**Comment by ayaka14732** [comment]
Thank you! Are you ready for publishing a new version of this font?

**Comment by redchenjs** [comment]
@ayaka14732 The latest font can be downloaded here [https://github.com/redchenjs/source-han-serif-classic/releases/tag/1.001](https://github.com/redchenjs/source-han-serif-classic/releases/tag/1.001)

**Comment by ayaka14732** [comment]
Thank you!
